{% assign blogLink = '//blog.rook.io/' %}
{% assign communityMeetingLink = '//github.com/rook/rook#community-meeting' %}
{% assign contributeLink = '//github.com/rook/rook/blob/master/CONTRIBUTING.md#how-to-contribute' %}
{% assign discussionLink = '//github.com/rook/rook/discussions' %}
{% assign featureRequestLink = '//github.com/rook/rook/issues' %}
{% assign newIssueLink = '//github.com/rook/rook/issues/new/choose' %}
{% assign gettingStartedLink = '/docs/rook/latest-release/Getting-Started/quickstart/' %}
{% assign githubLink = '//github.com/rook/rook' %}
{% assign latestDocs = '/docs/rook/latest-release/' %}
{% assign slackLink = '//slack.rook.io/' %}
{% assign twitterLink = '//twitter.com/rook_io' %}

{% assign cloudicalLink = '//cloudical.io/' %}
{% assign cncfLink = '//www.cncf.io' %}
{% assign cybozuLink = '//cybozu.com' %}
{% assign redHatLink = '//www.redhat.com/en/technologies/cloud-computing/openshift-data-foundation' %}
{% assign upboundLink = '//upbound.io' %}
{% assign cloudRaftLink = '//cloudraft.io/kubernetes-consulting' %}
